### ISSUE TITLE
Multi-threaded support

### ISSUE THREAD

**Issue by jagtapdeepak** [sahlberg/fuse-nfs#21]
Hey Guys, 
I am newbie to fuse world and would like to explore multi-threading for this fuse-nfs client.
Multi-threading will make it usable in environments with higher throughput. 
Could you please share your thoughts if it's feasible and worth doing it?
Thanks & Regards,
Deepak

**Comment by sahlberg** [comment]
The underlying libnfs library is in itself not currently threads safe, so for now any/all calls into libnfs would need to be protected by a futex. Serializing all access to libnfs this way should not be much of an issue as everything, except rpc_service() is fully async and non-blocking. Thus there is no real need or performance to gain by making it multithreaded.
(a sincle core/thread can easily keep 10GbE saturated).


Fuse-nfs on the other hand have a lot of opportunity for optimization.
The first obvious step would be to change the API that this fuse module uses.
Currently, to make it simple but slow it uses the synchronous fuse API.
This api is very simple and easy to use and you do not need to do any plumbing to integrate it
with an external event system. Because of this the current fuse-nfs will likely remain slow forever.


The fuse library also has a second type of API to use when building fuse filesystems.
That other API is fully async and you can build modules that are a LOT more scalable and faster.
But the API is a lot more complex and it also require you need to add in a proper event system
such as libevent or libtevent.
You can see an example on how to use that other fuse API in this (incomplete) smb filesystem : 
https://git.samba.org/?p=samba.git;a=tree;f=examples/fuse;h=de913c8ae65b75dc361cb8eb33be6b232cf2adea;hb=HEAD


I like to keep the current fuse module as a very simple, but slow, fuse filesystem.
But we could build a different version of fuse-nfs that uses that other async API instead.

I do not think I will have time right now to work on a proper high-performance nfs fuse filessystem but if you want to give it a try, you can likely start based on this driver:
https://git.samba.org/?p=samba.git;a=tree;f=examples/fuse;h=de913c8ae65b75dc361cb8eb33be6b232cf2adea;hb=HEAD

**Comment by jagtapdeepak** [comment]
Thanks Ronnie for insightful response! Fuse-nfs side changes should help improving the throughput.
I will start async version of fuse-nfs  as the time permits. Any opinion whether to go with libevent or boost:asyncio?

Best Regards,
Deepak

**Comment by sahlberg** [comment]
On Thu, May 11, 2017 at 12:16 PM, jagtapdeepak <notifications@github.com>
wrote:

> Thanks Ronnie for insightful response! Fuse-nfs side changes should help
> improving the throughput.
> I will start async version of fuse-nfs as the time permits. Any opinion
> whether to go with libevent or boost:asyncio?
>
I think that is up to you to decide.
You also have libtevent, which is very nice to work with but not as
portable as say libevent.


It probably also depends on how many and which platforms you want to
support outside of Linux and BSD.
Even windows have native fuse wrappers nowadays, it even have two such
wrappers!


If you want to support also building fuse modules for windows, I am fairly
sure at least libevent works natively for win32/64.
Not sure about other event systems.

**Comment by julian-hj** [comment]
Hi @sahlberg,

Based on this thread, I am wondering about the effects of setting `-t=1` on this executable, which would remove the `-s` option in the call to `fuse_main`.  From what I can see, that will likely fail on concurrent calls, particularly because it might re-use the same static `nfs` struct on multiple concurrent rpc calls.

Does that sound right to you?  And if so, do you think that making a copy of `nfs` for each rpc would fix it?  Or is removing the `-t` option the only safe thing to do without more elaborate code changes?

Thanks!

**Comment by sahlberg** [comment]
Sorry for the delay.

I have just added multithread safety to fuse-nfs   in the branch : async
Since virtually all the nfs_ functions we call (except nfs_opendir()) is non-blocking
the mutext will only be held very shortly and should allow great concurrency safely.

Please have a look at the async branch and test it.
I have only tested it very lightly since I dont really use this module much.

**Comment by julian-hj** [comment]
Hi @sahlberg thanks for the code updates!  This is a pretty exciting development if it can be made to work.

I tried testing it out quickly against our certification suite, but it seems to be hanging indefinitely when `touch`ing a new file in the mounted directory.

Do you see the same on your side?

**Comment by sahlberg** [comment]
Thanks for testing.

There is probably some deadlock in there.
Let me do some more serious testing during next week.

**Comment by jagtapdeepak** [comment]
Thanks Ronnie! Will try using the latest bits.

**Comment by sahlberg** [comment]
All,

Please try it again. the async branch should work much better now.
So we are making progress.

If you want to try this with nfsv4  you MUST update and install libnfs from
current master
as it was missing utime() emulation which fuse needs.


Reason why nfsv4 is important is that with nfsv4  we will be able to add
lockf() and fcntl()-locking
at some stage to fuse-nfs.  libnfs now has both lockf() as well as
fcntl()-locking for v4  so we only need
some semi-trivial plumbing to get it into fuse-nfs.
First we need to get the async code into shape so we are multithread safe.

I have little time currently and only managed to test manually for a
limited time.
Please review the code and/or do more tests, or send patches.
At some stage we should be able to go with the async branch and go full
multithreaded
but I need help in order to speed up the process.


Thanks
ronnie sahlberg

**Comment by julian-hj** [comment]
Thanks @sahlberg 

we have some automated testing that hammers the mount with simultaneous writes & reads & deletes.  When I have a moment I will try that with your latest updates and let you know.

**Comment by julian-hj** [comment]
@sahlberg 
First pass testing looks good--I'm not seeing the hanging behavior we had before, and we see modest speed improvements when making 100 simultaneous reads/writes/deletes of 1Mb files against an idle nfs server.

**Comment by julian-hj** [comment]
Just for posterity, I thought I'd record some of the timings we're seeing with fuse-nfs.  The test we are running spawns 100 goroutines simultaneously trying to write, then read, then delete a 1Mb file full of random text characters.  We do these in batches, so we collect timings to complete 100 simultaneous writes, for example, before commencing any read operations.

In addition to testing fuse-nfs, we also have another experimental approach that performs a nfsv3 kernel mount, and then fuse mounts that mount to another mount point with a fuse driver that only does the uid mapping.  We named that thing [mapfs](https://github.com/cloudfoundry/mapfs).

We ran the test suite multiple times, with fairly consistent results, so I have just grabbed representative data samples here rather than bothering with the necessary arithmetic to present average times.

Approach | Write Time | Read Time | Delete Time
--- | --- | --- | ---
original fuse-nfs | 20.383905 | 1.780002 | 0.266097
async fuse-nfs | 17.421563 | 0.840284 | 0.239933
async fuse-nfs with -t=1 | 16.965497 | 0.792334 | 0.137996
mapfs + nfs kernel mount | 12.941298 | 0.235822 | 0.492286

I'm not sure why we see such a consistent difference in read & write times, except perhaps that we are explicitly setting wsize and rsize in the kernel mount, and that's not an option in fuse-nfs.  I'm also not sure why deletes would be consistently slower in the other approach.

**Comment by sahlberg** [comment]
Thanks for testing.

That looks like pretty nice improvement in performance compared to the sync
version.

**Comment by sahlberg** [comment]
Thanks. Very nice improvements.

Could you also try it with fuse-nfs using NFSv4 ?
You need the latest version of libnfs to do this.

Libnfs uses a lot of compounding for its operations so anything that is
either metadata intensive or accessing deep directory structures should
become significantly faster with libnfs/NFSv4

**Comment by sahlberg** [comment]
I have merged the async code into master now.
